### ISSUE TITLE
Ver1.00時点でのUI要素課題

### ISSUE THREAD

**Issue by minagawa-korg** [hariya-korg/SamplingReverberator#11]
ver1.00時点での課題

・音声再生問題
	プレーヤーに読み込んだファイル名表示
	読み込むまでプレーヤー操作不能に

・Monitor
	インパルスの波形取得・Monitorでの描画
	リバーブ描画・スペアナなど

・WebGL
	できればWebGLで描画したい
	パーティクル等WebGLを活かした面白い描画

・各レベルメータの表示問題
	塗りがぼやけている点
	負荷軽減の為WebGLに渡して描きたい

・プリセットのスクロールバー
	いかにもな見た目なのでもう少しスマートなものに

・LIMIT等チェックボックス類
	クリックで色が変わるボタンなどで代替していきたい

・サンプル-録音画面切り替え
	録音画面実装に向け切り替え用のTabを用意したい

・ノブの方向
	現在はぐるっと時計回りに動かす必要あり
	動かしにくいので上下の動きだけで動かしたい
	
/******************* ほか *******************/
・本当にフラット的な画面のままでよいのか
	（動作負荷も考えるとあまり装飾もできないけれど....）

・コードのリファクタリング等
	特にCSSが行き当たりばったりで書かれたままなので
	非常に汚くなっている

**Comment by minagawa-korg** [comment]
Ver1.10追記

・画面サイズ
画面のピクセル数を取得して自動でズームする形にしたい
また、75%未満に縮小するとスクロールボックスで崩壊するため、
MIN-MAXの指定をしたい

・audio control
表示がブラウザとOSにかなりの影響を受けるため
できれば非表示にした上で別箇UIを作成し、jsで再生停止等をコントロールしたい

・選択中のリバーブ問題
どれが選択されているかがわかりにくいので選択されているリバーブを
スクロールボックス上に表示したい
インデックスの取得はできたものの、ファイル名の表示には至らなかった

![ver1 10](https://cloud.githubusercontent.com/assets/19897821/16512867/b49a337a-3f9a-11e6-9df8-e02e280ad8bf.png)

**Comment by minagawa-korg** [comment]
Ver1.10追記

・バイパス機能
現時点ではチェックボックスをアイコンにして画像を用意したのみで機能の実装は無し
ノードの付け替えをお願いします

**Comment by hariya-korg** [comment]
各項目ごとにIssueを作り直すのでこのIssueはcloseします.
