### ISSUE TITLE
limitを一度クリックすると消える.

### ISSUE THREAD

**Issue by hariya-korg** [hariya-korg/SamplingReverberator#6]
limitを一度クリックすると消えます. 修正お願いします.

**Comment by minagawa-korg** [comment]
limitのチェックボックスoffの状態のstyleを指定していなかったため、ブラウザデフォルトのチェックボックスのstyleに適用していたdisplay:none;が適用されて消えていました。
チェックボックスoffのstyleを指定することで修正しました。
