### ISSUE TITLE
波形表示時にキャンバスの縁が波形の色で塗りつぶされたままになる.

### ISSUE THREAD

**Issue by hariya-korg** [hariya-korg/SamplingReverberator#7]
波形表示時にキャンバスの縁が波形の色で塗りつぶされたままになります. 入力レベルを最大にし, 最大長のインパルス応答を選択し, limitのチェック外した状態でsin440を鳴らすと再現します.

**Comment by minagawa-korg** [comment]
キャンバスの背景のRをつけた部分に波形が描かれてしまうのが原因でした。
波形のY軸の描画領域をRの分減らすことで対応しました。
